background {
  monitor=
  path = /tmp/hyprlock/screenlock-wallpaper.png
  filter = blur(5px)
}

image {
  monitor=
  path=/tmp/hyprlock/screenlock-wallpaper-350.png
  size=350
  position=0,250
}

input-field {
    monitor=
    size=320,50
    outline_thickness=3
    outer_color = rgb(3964ba)
    inner_color = rgba(255, 255, 255, 0.5)
    background=ffffff80
    rounding=5
    halign=center
    valign=center
    position=0,-20
}

label {
  monitor=
  text=@$USER
  halign=center
  valign=center
  position=0,40
}

label {
  monitor=
  text=cmd[update:1000] echo "$TIME"
  font_size=60
  halign=right
  valign=bottom
  position=-100,100
}
